appname/urls.py
from django.urls import path

from appname import views

from appname.views import OrderReg, Orderlist ,Orderdetail , OrderUpdate, OrderDelete 

app_name='appname'

urlpatterns = [
    path('home', views.home, name = "home"),
    path('product', views.product, name = "product"),
    path('service', views.service, name = "service"),
    path('contact', views.contact, name = "contact"),
    path('aboutus', views.aboutus, name = "aboutus"),
    

   path('Orderreg', OrderReg.as_view(), name = 'Orderreg'),
   path('<pk>/Orderdetail', Orderdetail.as_view(), name = 'Orderdetail'),
   path('',Orderlist.as_view(), name = 'Orderlist'),
   path('<pk>/Orderupdate',OrderUpdate.as_view(),name = 'Orderupdate'),
   path('<pk>/Orderdelete', OrderDelete.as_view(), name = 'Orderdelete'),


### for get ad post
    path('dhana',views.dhana, name = 'dhana'),
    path('get1', views.get1, name = 'get1'),
    path('post1', views.post1, name = 'post1'),

###  for Fnuction based view.
    path('form', views.form,name  = 'form'), ##Order registration
    path('Orders', views.Order, name = "Orders"), #Orderlist
    path('detail/<int:id>', views.detail, name = 'detail'), # Order Detail
    path('update/<int:id>', views.update, name = 'update'), # Stuudent update
    path('delete/<int:id>', views.delete, name = 'delete'), #Order Update

### for user registratio, sign-in sign-out
    path('index', views.index, name = 'index'),
    path('register', views.register, name = 'register'),
    path('login_reg', views.login_reg, name = 'login_reg'),
    path('logout', views.logoutuser, name = 'logout'),

    
    path('', views.home, name='home'),
    path("image",views.image, name='image'),
    path('images', views.images, name='images'),
    
    path('product', views.product, name='product'),
    path('products', views.products, name='products'),
    path('order/<int:id>', views.order, name='order'),
    path('kart', views.kart  , name='kart '),
   
    
]



projectname/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('appname.urls')),
    path('Dhanalaxshmi/', include('Dhanalaxshmi.urls')),
]

templates/aboutus.html
{% load static %}
{% include 'base.html' %}

{% block content %}


<!-- page title -->
<section class="page-title-alt bg-primary position-relative">
    <div class="container">
      <div class="row">
        <div class="col-12">
         <u><b> <h1 class="text-white font-tertiary">ABOUT US</h1></b></u>
        </div>
      </div>
    </div>
    
   
  <!-- /page title -->
  
  <!-- about -->
  <section class="section pt-5">
    <div class="container">
      <div class="row">
        <div class="col-md-8">
          <h3>
            Hello,this is POTTURU VENKATESH generously welcoming you all to our "LAKSHMI STORES".
            This store will provide you various groceries,vegetables,snacks,cool drinks,fruits,etc...available for home delivery for near by places from store.
             We havebeen in this field for past 25 years and we always thank our customers for this affection and looking forward to keep it for more years. 
             We will always sell the goods at right price and we are trying to give more facilities to increase customer satisfaction.
             We always been in front in giving back and helping the people who were in needy through our donations..
             We hope you will enjoy journey with our stores....This is a short intro about us...Once again thank you for visiting our website..
          </h3>
        </div>
        <div class="col-md-4 text-center drag-lg-top">
          <div class="shadow-down mb-4">
            <img src="{% static 'I/L.jpg' %}" alt="author" class="img-fluid w-100 rounded-lg border-thick border-white">
          </div>
          
          <h4>LAKSHMI STORES</h4>
        </div>
      </div>
    </div>
  </section>
  <!-- /about -->
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Django Project</title>
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
   <style>
    body {
        background-color: grey; /* Replace this with your desired grey color code */
        color: antiquewhite;
    }
</style>
</head>
  <body>
    
            <nav class="navbar navbar-expand-lg bg-dark border-bottom border-body" data-bs-theme="dark">
          

        <div class="container-fluid">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'appname:home'%}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dropdown
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{% url 'appname:product'%}">Product</a></li>
                  <li><a class="dropdown-item" href="{% url 'appname:service'%}">Service</a></li>
                  <li><a class="dropdown-item" href="{% url 'appname:contact'%}">Contact</a></li>
                  <li><a class="dropdown-item" href="{% url 'appname:aboutus'%}">About-us</a></li>
                  
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="{% url 'appname:Orderlist'%}">Orders</a></li>
                </ul>
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'appname:dhana'%}">GET and POST</a>
                </li>

                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'appname:Orders'%}">FBV</a>
                </li>
              </li>
              
            </ul>
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
            </nav>
        {% block content %}  {% endblock %}
    
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
  
</body>
</html>

templates/base1.html
<html>

<head>
    <!-- Add the Bootstrap CSS link -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        body {
            background-color: grey; /* Replace this with your desired grey color code */
        }
    </style>
</head>

<body>
    <!-- Content with grey background -->
    <div class="container-fluid bg-secondary py-5">
        <h1>Hello, this is a grey background using Bootstrap!</h1>
        <p>This is some content on the grey background.</p>
        {% block content %}{% endblock %}

    </div>

    <!-- Add the Bootstrap JS and jQuery scripts (optional) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</body>

</html>